---
- name: Create data dir
  become: yes
  file:
    state: directory
    path: "{{ zookeeper_data_dir }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_user }}"
    
- name: Create log dir
  become: yes
  file:
    state: directory
    path: "{{ zookeeper_log_dir }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_user }}"

- name: Create myid file
  become: yes
  template:
    dest: "{{ zookeeper_myid_file }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_user }}"
    mode: 0755
    src: myid.j2
  notify:
    - restart zookeeper

- name: Create zookeeper properties file
  become: yes
  template:
    dest: "{{ zookeeper_properties_file }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_user }}"
    mode: 0755
    src: zookeeper.properties.j2
  notify:
    - restart zookeeper
      
- name: Create Zookeeper service
  become: yes
  template:
    dest: "{{ zookeeper_service }}"
    mode: 0755
    owner: root
    src: zookeeper.service.j2
  notify:
    - reload zookeeper
    - restart zookeeper

    
