---

- include_role:
    name: service
  vars:
    service_user: "{{ zk_user}}"
    service_home: "{{ zk_home}}"
    service_file: "{{ zk_service_file }}"
    service_data_dir: "{{ zk_data_dir }}"
    service_log_dir: "{{ zk_log_dir }}"
    service_properties_template: "{{ zk_properties_template }}"
    service_properties_file: "{{ zk_properties_file }}"
    service_name: "{{ zk_service_name }}"
    service_description: "{{ zk_service_description }}"
    service_start_command: "{{ zk_start_command }}"
    service_stop_command: "{{ zk_stop_command }}"
    service_jmx_port: "{{ zk_jmx_port }}"
        
- name: Create Zookeeper myid file
  template:
    dest: "{{ zk_myid_file }}"
    owner: "{{ zk_user }}"
    group: "{{ zk_user }}"
    mode: 0755
    src: myid.j2
  notify:
    - "restart {{ zk_service_name }}"
