version: '3.4'

services:
  producer:
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    image: producer
    ports:
      - "8081:8080"
        
  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    image: consumer