version: '3.4'

services:
  
  producer:
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    image: producer
    ports:
      - "8081:8080"
    networks:
      default:
        aliases:
           - producer
        
  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    image: consumer
    networks:
      default:
        aliases:
           - consumer
    
  loadgen:
    build:
      context: .
      dockerfile: ./loadgen/Dockerfile
    image: loadgen
    ports:
     - "8089:8089"
    networks:
      default:
        aliases:
           - loadgen
    command: -f locustfile.py