kafka_download_filename: "kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
kafka_download_url: "{{ kafka_download_mirror_prefix }}/{{ kafka_version }}/{{ kafka_download_filename }}"
kafka_versioned_home_dir: "{{ kafka_install_dir }}/{{ kafka_download_filename | regex_replace('(kafka_[\\d\\.]+-[\\d\\.]+).tgz$', '\\1')}}"
kafka_home_dir: "{{ kafka_install_dir }}/kafka"