service_description: Apache Kafka
service_start_command: "{{ service_home }}/bin/kafka-server-start.sh {{ service_properties_file }}"
service_stop_command: "{{ service_home }}/bin/kafka-server-stop.sh"

listeners:
  - protocol: PLAINTEXT
    host: 0.0.0.0
    port: 9092
    
advertised_listeners:
  - protocol: PLAINTEXT
    host: 127.0.0.1
    port: 9092