---
- name: start zookeeper
  become: yes
  systemd:
    name: zookeeper
    state: started

- name: stop zookeeper
  become: yes
  systemd:
    name: zookeeper
    state: stopped

- name: restart zookeeper
  become: yes
  systemd:
    name: zookeeper
    state: restarted

- name: reload zookeeper
  become: yes
  systemd:
    name: zookeeper
    daemon_reload: yes