---

- name: Remove any existing Docker packages
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc 
    state: absent
    update_cache: yes
    
- name: Install Docker prerequisites
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest
    update_cache: yes
    
- name: Add Docker's GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    
- name: Add Docker's apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    
- name: Install Docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
    
- name: Install Docker Compose
  apt:
    pkg: docker-compose
    state: latest
    update_cache: yes