---
- name: Create Kafka Service
  hosts: kafkabrokers
  become: yes
    - name: service
      vars:
        service: kafka
        advertised_listeners:
          - protocol: PLAINTEXT
            host: "{{ private_ip }}"
            port: "{{ advertised_listener_port }}"
            
        
