- hosts: zookeeper
  vars:
  roles:
    - name: newrelic.newrelic-infra
      vars:
        nrinfragent_config:
          license_key: {{ new_relic_license_key }}
          verbose: 3
          log_format: json
        nrinfragent_integrations: {{ nrinfragent_integrations }}

  # tasks:

      