- name: Install Zookeeper
  hosts: zookeepernodes
  pre_tasks:
    - set_fact:
        zknodes: "{{ zknodes }} + [ '{{ hostvars[item][\'private_ip\'] }}' ]"
      with_items: "{{ groups['zookeepernodes'] | list}}"
      vars:
        zknodes: []
    - debug:
        var: zknodes
    - name: update apt
      become: yes
      apt:
        update_cache: yes
  roles:
    - name: sansible.zookeeper
      sansible_zookeeper_java_version: 11
      #sansible_zookeeper_hosts: "{{ groups['zookeepernodes'] | map(attribute='private_ip') | list }}"
      sansible_zookeeper_hosts: "{{ zknodes }}"



- name: Install Kafka Server
  hosts: kafkabrokers
  pre_tasks:
    - set_fact:
        zknodes: "{{ zknodes }} + [ '{{ hostvars[item]['private_ip] }}:{{sansible_zookeeper_port}}' ]"
      with_items: "{{ groups['zookeepernodes'] | list}}"
      vars:
        zknodes: []
    - debug:
        var: zknodes
    - name: update apt
      become: yes
      apt:
        update_cache: yes
  roles:
    - name: sansible.kafka
      sansible_kafka_java_version: 11
      #sansible_kafka_zookeeper_hosts: "{{ groups['zookeepernodes'] | map(attribute='private_ip') | product(sansible_zookeeper_port) | map('join', ':') | list}}"
      sansible_zookeeper_hosts: "{{ zknodes }}"
      sansible_kafka_server_properties:
        broker.id: "{{ broker_id }}"
        advertised.listeners: "PLAINTEXT://{{public_ip}}:{{ sansible_kafka_port }}"