---
- name: Zookeeper
  hosts: zookeepernodes
  become: yes
  roles:
    - name: newrelic.newrelic-infra
      vars:
        nrinfragent_config:
          license_key: "{{ new_relic_license_key }}"
          verbose: 1
          log_format: json
    - name: logging
      vars:
        service_name: zookeeper.service
        logging_tag_name: zookeeper
        server_log: /var/log/zookeeper/server.log
    - name: kafka-integration
    - name: zookeeper-node
